version: "3"
services:
  client:
    build: ./client
    stdin_open: true
    ports: 
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - api-server
  api-server:
    build: ./server
    ports:
      - "3001:3001"
    networks:
      - mern-app
    depends_on:
      - mysql
    restart: on-failure
    environment:
      DB_HOST: ${DATABASE_URL}
      JWT_SECRET: ${SECRET_KEY}
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - mern-app
    volumes:
      - mysql-data:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=strongrootpassword
    restart: always
networks:
  mern-app:
    driver: bridge
volumes:
  mysql-data:
    driver: local