version: "3.9"
services:
  client:
    container_name: client
    build: ./client
    platform: linux/x86_64
    ports:
      - "5000:5000"
    depends_on:
      api-server:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "lsof", "-t", "-i:5000"]  # Caso utilize outra porta interna para o front, altere ela aqui também
        timeout: 10s
        retries: 5

    networks:
      - mern-app
  api-server:
    container_name: api
    build: ./server
    platform: linux/x86_64
    restart: 'always'
    ports:
      - "3001:3001"
    volumes:
      - './server/src:/app/src'
    command: "yarn run start"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mern-app
    environment:
      DB_HOST: mysql://root:strongrootpassword@mysql:3306/consulfacil_DB
      JWT_SECRET: ${SECRET_KEY}
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  mysql:
    image: mysql:8
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    platform: linux/x86_64
    networks:
      - mern-app
    volumes:
      - mysql-data:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=strongrootpassword
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] 
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
networks:
  mern-app:
    driver: bridge
volumes:
  mysql-data:
    driver: local